#ifndef __MissFrame__
#define __MissFrame__

/**
@file
Subclass of MissFrameBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissFrameBase */
class MissFrame : public MissFrameBase
{
	protected:
		// Handlers for MissFrameBase events.
		//void OnPaint( wxPaintEvent& event );
        void OnEraseBackground( wxEraseEvent& event );
        void OnPTitleLeftDown( wxMouseEvent& event );
        void OnPTitleOnPaint( wxPaintEvent& event );
	public:
		/** Constructor */
		MissFrame( wxWindow* parent );
		~MissFrame();
	//// end generated class members
        wxBitmap m_bmBackGround;

};

#endif // __MissFrame__
