#ifndef __MissRemind__
#define __MissRemind__

/**
@file
Subclass of MissRemindBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

#include <windef.h>
#include <wingdi.h>
//// end generated include

/** Implementing MissRemindBase */
class MissRemind : public MissRemindBase
{
	public:
		/** Constructor */
		MissRemind( wxWindow* parent );
	//// end generated class members

	private:
        void OnLeftDown( wxMouseEvent& event );
        void OnTimer(wxTimerEvent& event);

    private:
        HWND                             m_hWnd;
        BLENDFUNCTION                    m_Blend;
        SIZE                             m_SizeWindow;
        wxBitmap                         m_bpUI;
};

#endif // __MissRemind__
