#ifndef __MissSetDTFormat__
#define __MissSetDTFormat__

/**
@file
Subclass of MissSetDTFormatBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissSetDTFormatBase */
class MissSetDTFormat : public MissSetDTFormatBase
{
	protected:
		// Handlers for MissSetDTFormatBase events.
		void OnActivate( wxActivateEvent& event );
		void OnCobDateTime( wxCommandEvent& event );

	public:
		/** Constructor */
		MissSetDTFormat( wxWindow* parent );
	//// end generated class members

};

#endif // __MissSetDTFormat__
