#ifndef __MissSetWeekDay__
#define __MissSetWeekDay__

/**
@file
Subclass of MissSetWeekDayBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissSetWeekDayBase */
class MissSetWeekDay : public MissSetWeekDayBase
{
public:
    /** Constructor */
    MissSetWeekDay( int nWeekDay, wxWindow* parent );
    //// end generated class members
    void OnActivate( wxActivateEvent& event );

private:
    wxCheckBox *m_szWeekBox[7];
};

BEGIN_DECLARE_EVENT_TYPES()
    DECLARE_LOCAL_EVENT_TYPE(wxEVT_MCWD_EVENT, -1)
END_DECLARE_EVENT_TYPES()
#endif // __MissSetWeekDay__
