#ifndef __MissAbout__
#define __MissAbout__

/**
@file
Subclass of MissAboutBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissAboutBase */
class MissAbout : public MissAboutBase
{
	protected:
		// Handlers for MissAboutBase events.
		void OnBtnUpdateClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MissAbout( wxWindow* parent );
	//// end generated class members

};

#endif // __MissAbout__
