#ifndef __MissSetDTFormat__
#define __MissSetDTFormat__

/**
@file
Subclass of MissSetDTFormatBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissSetDTFormatBase */
class MissSetDTFormat : public MissSetDTFormatBase
{
	protected:
		// Handlers for MissSetDTFormatBase events.
		void OnActivate( wxActivateEvent& event );
		void OnCobDateTime( wxCommandEvent& event );
        void OnDateTimeText( wxCommandEvent& event );

	public:
		/** Constructor */
		MissSetDTFormat(int nType, const wxString& strFormat, wxWindow* parent );
	//// end generated class members

    protected:
        int GetSelectByFormatString(const wxString & strFormat);

    private:
        int m_nType;

};

BEGIN_DECLARE_EVENT_TYPES()
    DECLARE_LOCAL_EVENT_TYPE(wxEVT_MCDTF_EVENT, -1)
END_DECLARE_EVENT_TYPES()

#endif // __MissSetDTFormat__
