#ifndef __MissSetTimer__
#define __MissSetTimer__

/**
@file
Subclass of MissSetTimerBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissSetTimerBase */
class MissSetTimer : public MissSetTimerBase
{
	public:
		/** Constructor */
		MissSetTimer( wxWindow* parent );
	//// end generated class members

};

#endif // __MissSetTimer__
