#ifndef __MissTheme__
#define __MissTheme__

/**
@file
Subclass of MissThemeBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include
class MissSkin;


/** Implementing MissThemeBase */
class MissTheme : public MissThemeBase
{
	protected:
		// Handlers for MissThemeBase events.
		void OnInitDialog( wxInitDialogEvent& event );
		void OnBtnBGPathClick( wxCommandEvent& event );
		void OnCobLocaleSelect( wxCommandEvent& event );
		void OnlstItemDeselect( wxListEvent& event );
		void OnlstItemSelect( wxListEvent& event );
		void OnBtnAddItem( wxCommandEvent& event );
		void OnBtnDeleteItem( wxCommandEvent& event );
		void OnEdtNameKillFocus( wxFocusEvent& event );
		void OnCbtnShowClick( wxCommandEvent& event );
		void OnEdtContentKillFocus( wxFocusEvent& event );
		void OnBtnFont( wxCommandEvent& event );
		void OnBtnColor( wxCommandEvent& event );
		void OnSldAlignScrollThumbRelease( wxScrollEvent& event );
		void OnSpXChange( wxSpinEvent& event );
		void OnSpYChange( wxSpinEvent& event );
	public:
		/** Constructor */
		MissTheme( wxWindow* parent );
	//// end generated class members
	public:
        void SetDataSrc(shared_ptr<MissSkin>& pSkin);

	protected:
        void EnableItemSet(bool bEnable);
        void LoadThemeOption();
        void UpdateEdtAlignText();
        void SendUpdateEvent();
    private:
        int m_nThemeItem;
        shared_ptr<MissSkin> m_pSkin;
};

#endif // __MissTheme__
