#ifndef __MissRemind__
#define __MissRemind__

/**
@file
Subclass of MissRemindBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"


#include <windef.h>
#include <wingdi.h>
//// end generated include

/** Implementing MissRemindBase */

class MissRemindSkin;

class MissRemind : public MissRemindBase
{
	public:
		/** Constructor */
		MissRemind(const std::vector<wxString> &vecContent, wxWindow* parent );
	//// end generated class members
        ~MissRemind()
        {
            std::cout<<"~MissRemind"<<std::endl;
        }

    protected:
        void OnClose( wxCloseEvent& event );

	private:
        void OnLeftDown( wxMouseEvent& event );
        void OnTimer(wxTimerEvent& event);
        void OnDrawSkin();
        void OnDrawText();
        void OnInitEvent(wxCommandEvent& event);

    private:
        HWND                             m_hWnd;
        BLENDFUNCTION                    m_Blend;
        SIZE                             m_SizeWindow;
        wxBitmap                         m_bpUI;
        MissRemindSkin                  *m_pRemindSkin;
        shared_ptr<wxTimer>              m_pTimer;
};

BEGIN_DECLARE_EVENT_TYPES()
    DECLARE_LOCAL_EVENT_TYPE(wxEVT_FIRST_EVENT, -1)
END_DECLARE_EVENT_TYPES()

#endif // __MissRemind__
