#ifndef __MissOption__
#define __MissOption__

/**
@file
Subclass of MissOptionBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"

//// end generated include

/** Implementing MissOptionBase */
class MissOption : public MissOptionBase
{
	protected:
		// Handlers for MissOptionBase events.
		void OnInitDialog( wxInitDialogEvent& event );
		void OnSkinChoChange( wxCommandEvent& event );
		void OnModifySkinBtnClick( wxCommandEvent& event );
		void OnZoomCbtnClick( wxCommandEvent& event );
		void OnZoomSldChanged( wxScrollEvent& event );
		void OnTransSldChanged( wxScrollEvent& event );
		void OnNtpBtnClick( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
		void OnOK( wxCommandEvent& event );

	public:
		/** Constructor */
		MissOption( wxWindow* parent );
	//// end generated class members

};

#endif // __MissOption__
