#ifndef __MissRemind__
#define __MissRemind__

/**
@file
Subclass of MissRemindBase, which is generated by wxFormBuilder.
*/

#include "../Generated/GUIFrame.h"


#include <windef.h>
#include <wingdi.h>
//// end generated include

/** Implementing MissRemindBase */

class MissRemindSkin;

class MissRemind : public MissRemindBase
{
	public:
		/** Constructor */
		MissRemind(shared_ptr<MissRemindSkin> &pRemindSkin, wxWindow* parent );
	//// end generated class members


    protected:

	private:
        void OnLeftDown( wxMouseEvent& event );
        void OnTimer(wxTimerEvent& event);
        void OnDrawSkin();

    private:
        HWND                             m_hWnd;
        BLENDFUNCTION                    m_Blend;
        SIZE                             m_SizeWindow;
        wxBitmap                         m_bpUI;
        shared_ptr<MissRemindSkin>       m_pRemindSkin;
};

#endif // __MissRemind__
